c_compiler: gcc
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
fortran_compiler: gfortran
ignore_build_only_deps: numpy
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x.x
    max_pin: x.x.x
python: '2.7'
r_base: '3.5'
target_platform: linux-64
